# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bea835c2fe55dc4df5f607509eab7be025d7bb1413ef8a7b1ad696cedc88ca64aa1e4c4ec1059b13733851b3d71ffc1a340ff5ae51e8795d4857a6192f58c68e

test:
  secret_key_base: 99d7908891c5bea351715e903d7a245a7a34364bf59df9403c15dd80c2a33138da8ce165b1e55179b8ffc6c732c5621c304cf742b2eab9510dfb92a21f9f54f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
